SELECT DISTINCT 'EMPLOYEES' 
     ORDER BY DEPARTMENT_ID;


SELECT * FROM EMPLOYEES
     ORDER BY FIRST_NAME DESC;


SELECT SUM(DISTINCT salary) AS 'Salary'
FROM employees;


SELECT AVG(salary)
FROM employees ;

SELECT COUNT(*) FROM employees;


SELECT COUNT(*) FROM employees 
WHERE; 


SELECT UCASE(Name) AS FIRST_NAME
FROM Employees;


SELECT SUBSTR(FIRST_NAME, 1, 3)
FROM Employees;


SELECT CONCAT(FIRST_NAME, LAST_NAME)
    FROM employees;


SELECT TRIM(FIRST_NAME) 
	FROM employees;


SELECT FIRST_NAME,LAST_NAME ,LEN(FIRST_NAME,LAST_NAME) as LengthOfName
FROM Employees;


SELECT * FROM `employees` LIMIT 0, 10;