SELECT DEPARTMENT_NAME, LOCATION_ID, STREET_ADDRESS, CITY, STATE_PROVINCE, COUNTRY_NAME 
	FROM departments NATURAL JOIN locations
	NATURAL JOIN countrie

SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_ID, DEPARTMENT_NAME 
	FROM employees JOIN departments


SELECT FIRST_NAME, LAST_NAME, JOB_TITLE, DEPARTMENT_ID, DEPARTMENT_NAME
	FROM employees, departments, jobs, locations
	WHERE employees.JOB_ID = jobs.JOB_ID
	WHERE location.city="London"


SELECT DEPARTMENT_NAME, COUNT(employees.DEPARTMENT_ID) 
	FROM departments JOIN employees
	ON departments.DEPARTMENT_ID = employees.DEPARTMENT_ID
	GROUP BY employees.DEPARTMENT_ID


SELECT FIRST_NAME, LAST_NAME, HIRE_DATE
	FROM employees
	WHERE HIRE_DATE > (SELECT HIRE_DATE FROM employees WHERE LAST_NAME = 'Jones')