1.
SELECT FIRST_NAME, LAST_NAME
	FROM employees 
	WHERE SALARY > SELECT SALARY FROM employees WHERE LAST_NAME = 'Bull'

2.
SELECT FIRST_NAME, LAST_NAME
	FROM employees WHERE department_name = "IT"

3.
SELECT FIRST_NAME, LAST_NAME
	FROM employees WHERE JOB_ID = 'MAN'

4.
SELECT FIRST_NAME, LAST_NAME 
	FROM employees WHERE SALARY > (SELECT AVG(SALARY) FROM employees)

5.
SELECT FIRST_NAME, LAST_NAME 
	FROM employees WHERE min_salary = salary

6.
SELECT FIRST_NAME, LAST_NAME, MIN(SALARY)
	FROM employees GROUP BY DEPARTMENT_ID

7.


8.
SELECT * FROM employees ORDER BY EMPLOYEE_ID DESC LIMIT 10